name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "22 04 * * *" # Daily at 9:22 PM PDT, 8:22 PM PST.
  workflow_dispatch:

permissions:
  contents: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.base.sha }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

defaults:
  run:
    shell: bash

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1

  check:
    name: Check
    if: ${{ needs.pre_job.outputs.should_skip != 'true' || github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 25
    needs: pre_job

    steps:
      - name: Checkout sources
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install nightly toolchain (minimal-versions check)
        run: rustup toolchain install nightly --profile minimal

      - name: Install cargo-msrv
        uses: taiki-e/cache-cargo-install-action@f9eed3e4680f27610dc6d8c67be1b88593f7dade # v3.0.6
        with:
          tool: cargo-msrv

      - name: Run check.bash
        run: ./check.bash
